version: '3'

services:
  postgres-test:
    image: postgres
    environment:
      POSTGRES_DB: gym
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5439:5432"
    networks:
      - gym-network-test

  activemq-test:
    image: rmohr/activemq
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
    ports:
      - "8199:61616"
      - "8169:8161"
    networks:
      - gym-network-test

  mongodb-test:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27019:27017"
    networks:
      - gym-network-test

networks:
  gym-network-test:
