spring:
  application:
    name: MAIN
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/gym
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
server:
  port: 8080
auth-bearer-token: 'myBearerToken'
trainer-workload-service-bearer-token: 'myBearerToken2'
brute-force-protector:
  max-attempt: 3
  block-time-minute: 5
secret-key: 'mySecretKey1234567890mySecretKey1234567890mySecretKey1234567890mySecretKey1234567890'
audience-type: 'service'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost

---

spring:
  profiles: test
  datasource:
    url: jdbc:postgresql://localhost:5432/gym_test
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
server:
  port: 8000
auth-bearer-token: 'myBearerToken'
trainer-workload-service-bearer-token: 'myBearerToken2'
brute-force-protector:
  max-attempt: 3
  block-time-minute: 5
secret-key: 'mySecretKey1234567890mySecretKey1234567890mySecretKey1234567890mySecretKey1234567890'

---

spring:
  profiles: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/gym_prod
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
server:
  port: 8082
auth-bearer-token: 'myBearerToken'
trainer-workload-service-bearer-token: 'myBearerToken2'
brute-force-protector:
  max-attempt: 3
  block-time-minute: 5
secret-key: 'mySecretKey1234567890mySecretKey1234567890mySecretKey1234567890mySecretKey1234567890'