spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/gym
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
server:
  port: 8080
auth:
  bearer:
    token: 'myBearerToken'
brute-force-protector:
  max-attempt: 3
  block-time-minute: 5
secret-key: 'mySecretKey1234567890mySecretKey1234567890mySecretKey1234567890mySecretKey1234567890'

---

spring:
  profiles: test
  datasource:
    url: jdbc:postgresql://localhost:5432/gym_test
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
server:
  port: 8000
auth:
  bearer:
    token: 'myBearerToken'
brute-force-protector:
  max-attempt: 3
  block-time-minute: 5
secret-key: 'mySecretKey1234567890mySecretKey1234567890mySecretKey1234567890mySecretKey1234567890'

---

spring:
  profiles: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/gym_prod
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
server:
  port: 8082
auth:
  bearer:
    token: 'myBearerToken'
brute-force-protector:
  max-attempt: 3
  block-time-minute: 5
secret-key: 'mySecretKey1234567890mySecretKey1234567890mySecretKey1234567890mySecretKey1234567890'