alter table if exists trainee drop constraint if exists FKk83ug7xirx0mc92sep3t5eo6g;

alter table if exists trainees_trainers drop constraint if exists FK6c964npvycyisxmka9qm9soqm;

alter table if exists trainees_trainers drop constraint if exists FKlcfqudqyqbr9h9e8kk9gis29d;

alter table if exists trainer drop constraint if exists FKd1is9muo3jbbbr9rhp2f14bca;

alter table if exists training drop constraint if exists FKi2dctw34e0xl50d8tsnrre7te;

alter table if exists training drop constraint if exists FK7r3b25ygw5bdjamojskmpk0b9;

drop table if exists trainee cascade;

drop table if exists trainees_trainers cascade;

drop table if exists trainer cascade;

drop table if exists training cascade;

drop table if exists usr cascade;

drop table if exists training_type cascade;

create table trainee (
    id int8 generated by default as identity,
    address varchar(255),
    date_of_birth timestamp,
    username varchar(255),
    primary key (id)
);

create table trainees_trainers (
    trainer_id int8 not null,
    trainee_id int8 not null,
    primary key (trainer_id, trainee_id)
);

create table trainer (
    id int8 generated by default as identity,
    training_type_id int4, username varchar(255),
    primary key (id)
);

create table training (
    id int8 generated by default as identity,
    duration int4 not null,
    training_date timestamp,
    training_name varchar(255),
    training_type int4,
    trainee_id int8,
    trainer_id int8,
    primary key (id)
);

create table training_type (
   id int2 not null,
    value varchar(255) not null,
    primary key (id)
);

create table usr (
    username varchar(255) not null,
    first_name varchar(255),
    is_active boolean not null,
    last_name varchar(255),
    password varchar(255),
    primary key (username)
);

alter table if exists trainee add constraint FKk83ug7xirx0mc92sep3t5eo6g foreign key (username) references usr;

alter table if exists trainees_trainers add constraint FK6c964npvycyisxmka9qm9soqm foreign key (trainee_id) references trainee;

alter table if exists trainees_trainers add constraint FKlcfqudqyqbr9h9e8kk9gis29d foreign key (trainer_id) references trainer;

alter table if exists trainer add constraint FKd1is9muo3jbbbr9rhp2f14bca foreign key (username) references usr;

alter table if exists training add constraint FKi2dctw34e0xl50d8tsnrre7te foreign key (trainee_id) references trainee on delete cascade;

alter table if exists training add constraint FK7r3b25ygw5bdjamojskmpk0b9 foreign key (trainer_id) references trainer;